########################
### Modify as needed ###
########################
data_dir: ../data/log_monitor_agent
results_dir: ../output/analysis_results
overwrite: true
max_workers: 10
run_name: my_experiment
evaluation_criteria: null
predefined_issues: null

# Model Configuration
inference_backend: litellm
endpoint_url: null
provider: openai
eval_model_name: gpt-4o
eval_model_params:
  temperature: 0.0
  max_tokens: 8096


# keep as is
from_raw_traces: true
agent_framework: langgraph
observability_framework: mlflow
separate_tools: false
run_step_by_step: true
run_full_trajectory: false
